### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by k-syusteem** [mimecorg/vuido#14] opened 2018-05-23 18:41 UTC
### Hi @mimecorg !

I am a designer and I am good at designing logos, do you need a logo for your project "vuido". I will make it and it is for free I give to you.

**Comment by ErichDonGubler** [comment] 2018-05-23 19:00
This is a dupe of https://github.com/mimecorg/vuido/issues/6. ;)

**Comment by k-syusteem** [comment] 2018-05-23 19:14
@ErichDonGubler Thank you!

**Closed** 2018-05-23 19:14 UTC
